# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # Specify the package manager (e.g., npm or yarn)
    directory: "/" # Location of the package.json file (root directory)
    schedule:
      interval: "daily" # Frequency of updates (e.g., daily, weekly, monthly)
    commit-message:
      prefix: "deps" # Optional: Customize the commit message prefix
